apiVersion: v1
kind: Namespace
metadata:
  name: llm-system
  labels:
    app.kubernetes.io/name: llm-system
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: llm-system-quota
  namespace: llm-system
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "10"
    pods: "50"
    services: "20"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: llm-system-network-policy
  namespace: llm-system
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: llm-system
    - namespaceSelector:
        matchLabels:
          name: kube-system
  egress:
  - {}